### PR TITLE
Test Sphinx theme

### PR DESCRIPTION
**Pull request by jank324**
Switch docs to Awesome Sphinx Theme to test it.

### CODE REVIEW

**Review by cr-xu — APPROVED** [review]

**Comment by cr-xu** [comment]
Somehow it shows merging is blocked for me
image
But this seems just a fast-forward. Also, we didn't change any branch protection rules, right?

**Comment by jank324** [comment]
> Somehow it shows merging is blocked for me image But this seems just a fast-forward. Also, we didn't change any branch protection rules, right?

It says the same ... I really don't see why though. Maybe it's because the PR is very old?

I'm inclined to bypass the branch protections for this one if you also don't see any reasons why we shouldn't.

**Comment by jank324** [comment]
We didn't change the branch protection rules recently. But given the age of the PR, it is possible we changed them since creating it.

**Comment by cr-xu** [comment]
> It says the same for me ... I really don't see why though. Maybe it's because the PR is very old?
> 
> I'm inclined to bypass the branch protections for this one if you also don't see any reasons why we shouldn't.


Sounds good, let's just do that.

**Pull request merged**
