### PR TITLE
Implement vectorized split

### PR DESCRIPTION
**Pull request by Hespe**
## Description

The current split implementation is not vectorized and fails on vectorized elements

## Motivation and Context

The implementation is changed to treat `resolution` as an upper bound on the length of the resulting subelements. This ensures that the elements will be divided into equally many subelements, even if the vectorized lengths are different.

Because of this change, the subelements are now assigned uniform length, instead of having the final element fill the gap to the total length. This could be considered to be a __breaking change__, but most likely no one relied on that exact behaviour.

- [x] I have raised an issue to propose this change (#227)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist

- [x] I have updated the changelog accordingly (**required**).
- [ ] My change requires a change to the documentation.
- [x] I have updated the tests accordingly (_required for a bug fix or a new feature_).
- [ ] I have updated the documentation accordingly.
  
  
- [x] I have reformatted the code and checked that formatting passes (**required**).
- [x] I have have fixed all issues found by `flake8` (**required**).
- [x] I have ensured that all `pytest` tests pass (**required**).
- [ ] I have run `pytest` on a machine with a CUDA GPU and made sure all tests pass (**required**).
- [x] I have checked that the documentation builds (**required**).

Note: We are using a maximum length of 88 characters per line.

### CODE REVIEW

**Comment by Hespe** [comment]
It seems that I have accidentally fixed two tests that previously failed and are now marked as _xPassed_.

**Comment by jank324** [comment]
> It seems that I have accidentally fixed two tests that previously failed and are now marked as _xPassed_.

You mean tests that were marked as expected to fail but now they pass? I'm confused.

**Comment by Hespe** [comment]
> > It seems that I have accidentally fixed two tests that previously failed and are now marked as _xPassed_.
> 
> You mean tests that were marked as expected to fail but now they pass? I'm confused.

Exactly, `test_drift_end` and `test_quadrupole_end` are currently marked as _xFail_ and are passing now.

**Comment by Hespe** [comment]
Looks like the MacOS runner failed the speed test for the previous commit, not sure why.

**Comment by Hespe** [comment]
We might want to also include vectorized tests for the Solenoid and Undulator, but that is currently blocked on #232

**Comment by jank324** [comment]
> We might want to also include vectorized tests for the Solenoid and Undulator, but that is currently blocked on #232

#232 is now merged into `master` and this PR.

**Review by jank324 — APPROVED** [review]

**Comment by Hespe** [comment]
> > We might want to also include vectorized tests for the Solenoid and Undulator, but that is currently blocked on #232
> 
> #233 (which fixes #232) is now merged into `master` and this PR.

Both cases are now also tested in vectorized form and passing.

**Review by cr-xu — APPROVED** [review]
Looks good to me.

**Pull request merged**
