### PR TITLE
Implement moving to `device` and changing `dtype`

### LINKED ISSUE #113: Moving elements and beams to devices doesn't work
It should be possible, like with any other PyTorch Module, to move Elements and Beams by calling

```python
element = element.to(device)
```

or

```python
element = element.cpu()
```

or

```python
element = element.cuda()
```

Unfortunately, this doesn't work right now.

### PR DESCRIPTION
**Pull request by jank324**
## Description

Implements that elements and beams can easily be moved to different devices and their beam types can be changes, like you would expect from a normal `torch.nn.Module`.

## Motivation and Context

This is normal for `torch.nn.Module` and would make working with different devices and dtypes in Cheetah much easier. Closes #113.

- [x] I have raised an issue to propose this change (required for new features and bug fixes)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist

- [x] I have updated the changelog accordingly (**required**).
- [x] My change requires a change to the documentation.
- [x] I have updated the tests accordingly (_required for a bug fix or a new feature_).
- [ ] I have updated the documentation accordingly.
  
  
- [x] I have reformatted the code and checked that formatting passes (**required**).
- [x] I have have fixed all issues found by `flake8` (**required**).
- [x] I have ensured that all `pytest` tests pass (**required**).
- [ ] I have run `pytest` on a machine with a CUDA GPU and made sure all tests pass (**required**).
- [x] I have checked that the documentation builds (**required**).

Note: We are using a maximum length of 88 characters per line

### CODE REVIEW

**Comment by jank324** [comment]
@cr-xu @ansantam if we do something like this in an Element's `__init__`

```python
self.register_buffer(
    "k1",
    (
        torch.as_tensor(k1, **factory_kwargs)
        if k1 is not None
        else torch.zeros_like(self.length)
    ),
)
```

everything just works. It almost like the PyTorch people thought of this. 😄💡

**Comment by jank324** [comment]
Can lines like
```python
factory_kwargs = {"device": device, "dtype": dtype}
```
then be removed?

**Comment by jank324** [comment]
Should `Aperture.is_active`, `Aperture.shape` and `Aperture.lost_particles` be registered as buffers?

**Comment by jank324** [comment]
> Can lines like
> 
> ```python
> factory_kwargs = {"device": device, "dtype": dtype}
> ```
> 
> then be removed?

In `torch.nn.Linear`, `factory_kwargs` are also used (in fact that's where I got it from). So I guess it should be considered PyTorch best practice.

**Comment by jank324** [comment]
@cr-xu please review carefully. This seemed too easy.

**Review by cr-xu — APPROVED** [review]
Looks good to me. Since all the tests are passing let's go with it. I guess we'll see in practice if anything breaks.

**Pull request merged**
